version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run:
          name: install
          command: yarn install --ignore-engines
      - save_cache:
          key: dependency-cache
          paths:
            - ./node_modules
